### ISSUE TITLE
[DS] Implement Set

### ISSUE THREAD

**Issue by phenax** [phenax/fp-collections-rs#3]

**Comment by melwyn-people-interactive** [comment]
This PR https://github.com/phenax/fp-collections-rs/pull/16 implements a basic set with add, remove and mem functions
We could add addition fp capabilities to the set by implementing `map` and `fold`
For a more complete set implementation we will need `union` & `intersect` (to implementing this we will have to figure out how to merge, join, etc. two set)

**Comment by melwyn95** [comment]
This PR https://github.com/phenax/fp-collections-rs/pull/16 implements a basic set with add, remove and mem functions
We could add addition fp capabilities to the set by implementing `map` and `fold`
For a more complete set implementation we will need `union` & `intersect` (to implementing this we will have to figure out how to merge, join, etc. two set)
